/**
 * Seed catalog — popular movies, TV shows, and books with genres/tags.
 * Users can also add custom titles not in the catalog.
 */
window.SEQUEL_CATALOG = [
  // —— Movies ——
  { id: "m-inception", type: "movie", title: "Inception", year: 2010, genres: ["scifi", "thriller", "mind-bending"], vibe: ["cerebral", "epic"], why: "Dream heists and layered reality" },
  { id: "m-interstellar", type: "movie", title: "Interstellar", year: 2014, genres: ["scifi", "drama", "space"], vibe: ["emotional", "epic"], why: "Love, time, and the stars" },
  { id: "m-dune", type: "movie", title: "Dune", year: 2021, genres: ["scifi", "epic", "adventure"], vibe: ["epic", "atmospheric"], why: "Desert empires and destiny" },
  { id: "m-parasite", type: "movie", title: "Parasite", year: 2019, genres: ["thriller", "drama", "dark-comedy"], vibe: ["sharp", "tense"], why: "Class warfare with a twist" },
  { id: "m-everything", type: "movie", title: "Everything Everywhere All at Once", year: 2022, genres: ["scifi", "comedy", "family"], vibe: ["wild", "heartfelt"], why: "Multiverse chaos and family love" },
  { id: "m-arrival", type: "movie", title: "Arrival", year: 2016, genres: ["scifi", "drama", "mind-bending"], vibe: ["quiet", "emotional"], why: "Language, time, and first contact" },
  { id: "m-getout", type: "movie", title: "Get Out", year: 2017, genres: ["horror", "thriller", "social"], vibe: ["tense", "smart"], why: "Horror with social bite" },
  { id: "m-spiderverse", type: "movie", title: "Spider-Man: Into the Spider-Verse", year: 2018, genres: ["animation", "superhero", "adventure"], vibe: ["fun", "stylish"], why: "Kinetic art and heart" },
  { id: "m-whiplash", type: "movie", title: "Whiplash", year: 2014, genres: ["drama", "music"], vibe: ["intense", "ambitious"], why: "Obsession and greatness" },
  { id: "m-her", type: "movie", title: "Her", year: 2013, genres: ["romance", "scifi", "drama"], vibe: ["intimate", "melancholy"], why: "Love in a digital age" },
  { id: "m-madmax", type: "movie", title: "Mad Max: Fury Road", year: 2015, genres: ["action", "adventure"], vibe: ["visceral", "epic"], why: "Non-stop desert chase" },
  { id: "m-la-la-land", type: "movie", title: "La La Land", year: 2016, genres: ["musical", "romance", "drama"], vibe: ["bittersweet", "stylish"], why: "Dreams vs. love in LA" },
  { id: "m-blade-runner-2049", type: "movie", title: "Blade Runner 2049", year: 2017, genres: ["scifi", "noir", "mystery"], vibe: ["atmospheric", "slow-burn"], why: "What makes us human" },
  { id: "m-the-batman", type: "movie", title: "The Batman", year: 2022, genres: ["superhero", "crime", "noir"], vibe: ["dark", "detective"], why: "Gritty Gotham detective story" },
  { id: "m-oppenheimer", type: "movie", title: "Oppenheimer", year: 2023, genres: ["biography", "drama", "history"], vibe: ["dense", "epic"], why: "The man behind the bomb" },
  { id: "m-barbie", type: "movie", title: "Barbie", year: 2023, genres: ["comedy", "fantasy", "social"], vibe: ["playful", "sharp"], why: "Pink satire with heart" },
  { id: "m-spirited", type: "movie", title: "Spirited Away", year: 2001, genres: ["animation", "fantasy", "adventure"], vibe: ["magical", "coming-of-age"], why: "Ghibli wonder and courage" },
  { id: "m-pride", type: "movie", title: "Pride & Prejudice", year: 2005, genres: ["romance", "period", "drama"], vibe: ["romantic", "witty"], why: "Classic sparks and banter" },
  { id: "m-john-wick", type: "movie", title: "John Wick", year: 2014, genres: ["action", "thriller"], vibe: ["stylish", "revenge"], why: "Ballet of bullets" },
  { id: "m-social-network", type: "movie", title: "The Social Network", year: 2010, genres: ["drama", "biography", "tech"], vibe: ["sharp", "ambitious"], why: "Friendship and founding Facebook" },

  // —— TV ——
  { id: "t-breaking-bad", type: "tv", title: "Breaking Bad", year: 2008, genres: ["crime", "drama", "thriller"], vibe: ["intense", "character-driven"], why: "Chemistry teacher turns kingpin" },
  { id: "t-succession", type: "tv", title: "Succession", year: 2018, genres: ["drama", "dark-comedy", "family"], vibe: ["sharp", "savage"], why: "Rich family power games" },
  { id: "t-the-bear", type: "tv", title: "The Bear", year: 2022, genres: ["drama", "comedy", "food"], vibe: ["anxious", "heartfelt"], why: "Kitchen chaos and found family" },
  { id: "t-stranger-things", type: "tv", title: "Stranger Things", year: 2016, genres: ["scifi", "horror", "adventure"], vibe: ["nostalgic", "fun"], why: "Kids vs the Upside Down" },
  { id: "t-the-office", type: "tv", title: "The Office", year: 2005, genres: ["comedy", "workplace"], vibe: ["comfort", "awkward"], why: "Dunder Mifflin forever" },
  { id: "t-severance", type: "tv", title: "Severance", year: 2022, genres: ["scifi", "thriller", "mystery"], vibe: ["eerie", "cerebral"], why: "Work-life split made literal" },
  { id: "t-shogun", type: "tv", title: "Shōgun", year: 2024, genres: ["history", "drama", "epic"], vibe: ["epic", "political"], why: "Feudal Japan intrigue" },
  { id: "t-andor", type: "tv", title: "Andor", year: 2022, genres: ["scifi", "thriller", "war"], vibe: ["grounded", "tense"], why: "Rebellion before the Rebellion" },
  { id: "t-the-last-of-us", type: "tv", title: "The Last of Us", year: 2023, genres: ["drama", "horror", "adventure"], vibe: ["emotional", "harsh"], why: "Surviving a fungal apocalypse" },
  { id: "t-arcane", type: "tv", title: "Arcane", year: 2021, genres: ["animation", "fantasy", "action"], vibe: ["stylish", "tragic"], why: "Sisters torn by progress" },
  { id: "t-ted-lasso", type: "tv", title: "Ted Lasso", year: 2020, genres: ["comedy", "sports", "feel-good"], vibe: ["warm", "kind"], why: "Optimism as a superpower" },
  { id: "t-dark", type: "tv", title: "Dark", year: 2017, genres: ["scifi", "mystery", "mind-bending"], vibe: ["dense", "dark"], why: "Time travel family knot" },
  { id: "t-fleabag", type: "tv", title: "Fleabag", year: 2016, genres: ["comedy", "drama"], vibe: ["raw", "witty"], why: "Grief, love, fourth wall" },
  { id: "t-mandalorian", type: "tv", title: "The Mandalorian", year: 2019, genres: ["scifi", "adventure", "western"], vibe: ["fun", "space-western"], why: "This is the way" },
  { id: "t-wednesday", type: "tv", title: "Wednesday", year: 2022, genres: ["mystery", "fantasy", "teen"], vibe: ["quirky", "gothic"], why: "Addams detective vibes" },

  // —— Books ——
  { id: "b-dune", type: "book", title: "Dune", year: 1965, author: "Frank Herbert", genres: ["scifi", "epic", "politics"], vibe: ["epic", "dense"], why: "The novel that defined desert power" },
  { id: "b-project-hail-mary", type: "book", title: "Project Hail Mary", year: 2021, author: "Andy Weir", genres: ["scifi", "adventure", "friendship"], vibe: ["fun", "smart"], why: "Science problem-solving in space" },
  { id: "b-circe", type: "book", title: "Circe", year: 2018, author: "Madeline Miller", genres: ["fantasy", "mythology", "literary"], vibe: ["lyrical", "feminist"], why: "Witch of Aiaia retold" },
  { id: "b-name-of-the-wind", type: "book", title: "The Name of the Wind", year: 2007, author: "Patrick Rothfuss", genres: ["fantasy", "adventure"], vibe: ["lyrical", "coming-of-age"], why: "A legend tells his story" },
  { id: "b-gone-girl", type: "book", title: "Gone Girl", year: 2012, author: "Gillian Flynn", genres: ["thriller", "mystery", "dark"], vibe: ["twisty", "unreliable"], why: "Marriage as a crime scene" },
  { id: "b-atomic-habits", type: "book", title: "Atomic Habits", year: 2018, author: "James Clear", genres: ["self-help", "productivity"], vibe: ["practical", "clear"], why: "Tiny changes, big results" },
  { id: "b-educated", type: "book", title: "Educated", year: 2018, author: "Tara Westover", genres: ["memoir", "biography"], vibe: ["raw", "inspiring"], why: "Leaving home for knowledge" },
  { id: "b-1984", type: "book", title: "1984", year: 1949, author: "George Orwell", genres: ["dystopia", "scifi", "classic"], vibe: ["bleak", "political"], why: "Big Brother is watching" },
  { id: "b-hobbit", type: "book", title: "The Hobbit", year: 1937, author: "J.R.R. Tolkien", genres: ["fantasy", "adventure", "classic"], vibe: ["cozy", "epic"], why: "Unexpected journey" },
  { id: "b-silent-patient", type: "book", title: "The Silent Patient", year: 2019, author: "Alex Michaelides", genres: ["thriller", "mystery", "psychological"], vibe: ["twisty", "page-turner"], why: "A woman who won't speak" },
  { id: "b-klara", type: "book", title: "Klara and the Sun", year: 2021, author: "Kazuo Ishiguro", genres: ["literary", "scifi", "drama"], vibe: ["quiet", "tender"], why: "An AI's devotion" },
  { id: "b-song-of-achilles", type: "book", title: "The Song of Achilles", year: 2011, author: "Madeline Miller", genres: ["mythology", "romance", "literary"], vibe: ["romantic", "tragic"], why: "Patroclus and Achilles" },
  { id: "b-six-of-crows", type: "book", title: "Six of Crows", year: 2015, author: "Leigh Bardugo", genres: ["fantasy", "heist", "ya"], vibe: ["clever", "found-family"], why: "Impossible heist crew" },
  { id: "b-sapiens", type: "book", title: "Sapiens", year: 2011, author: "Yuval Noah Harari", genres: ["history", "nonfiction", "science"], vibe: ["big-picture", "provocative"], why: "How humans took over" },
  { id: "b-thursday-murder", type: "book", title: "The Thursday Murder Club", year: 2020, author: "Richard Osman", genres: ["mystery", "comedy", "cozy"], vibe: ["cozy", "witty"], why: "Retirees solve murders" },
  { id: "b-narnia", type: "book", title: "The Lion, the Witch and the Wardrobe", year: 1950, author: "C.S. Lewis", genres: ["fantasy", "classic", "adventure"], vibe: ["magical", "classic"], why: "Wardrobe to Narnia" },
  { id: "b-martian", type: "book", title: "The Martian", year: 2011, author: "Andy Weir", genres: ["scifi", "adventure", "humor"], vibe: ["fun", "problem-solving"], why: "Science the crap out of this" },
  { id: "b-normal-people", type: "book", title: "Normal People", year: 2018, author: "Sally Rooney", genres: ["literary", "romance", "drama"], vibe: ["intimate", "raw"], why: "Modern love and class" },
  { id: "b-mistborn", type: "book", title: "Mistborn: The Final Empire", year: 2006, author: "Brandon Sanderson", genres: ["fantasy", "heist", "magic"], vibe: ["clever", "epic"], why: "Ash, metal, and rebellion" },
  { id: "b-gatsby", type: "book", title: "The Great Gatsby", year: 1925, author: "F. Scott Fitzgerald", genres: ["classic", "literary", "romance"], vibe: ["glamorous", "tragic"], why: "Green light across the bay" },
];
