/**
 * Seed catalog — movies, TV, books with genres + search keys for cover art.
 * Covers load live via free iTunes / Open Library APIs (cached in the browser).
 */
window.SEQUEL_CATALOG = [
  // —— New / recent movies ——
  { id: "m-dune2", type: "movie", title: "Dune: Part Two", year: 2024, genres: ["scifi", "epic", "adventure"], vibe: ["epic", "atmospheric"], why: "War for Arrakis continues", newRelease: true, posterQuery: "Dune Part Two" },
  { id: "m-wicked", type: "movie", title: "Wicked", year: 2024, genres: ["musical", "fantasy", "adventure"], vibe: ["spectacular", "emotional"], why: "Oz before Dorothy", newRelease: true, posterQuery: "Wicked 2024" },
  { id: "m-challengers", type: "movie", title: "Challengers", year: 2024, genres: ["drama", "romance", "sports"], vibe: ["sexy", "tense"], why: "Love triangle on the court", newRelease: true, posterQuery: "Challengers" },
  { id: "m-anora", type: "movie", title: "Anora", year: 2024, genres: ["comedy", "drama", "romance"], vibe: ["wild", "heartfelt"], why: "A whirlwind Brooklyn fairytale", newRelease: true, posterQuery: "Anora" },
  { id: "m-conclave", type: "movie", title: "Conclave", year: 2024, genres: ["thriller", "drama", "mystery"], vibe: ["tense", "cerebral"], why: "Secrets inside the Vatican vote", newRelease: true, posterQuery: "Conclave" },
  { id: "m-inside-out-2", type: "movie", title: "Inside Out 2", year: 2024, genres: ["animation", "family", "comedy"], vibe: ["fun", "emotional"], why: "New emotions, teen chaos", newRelease: true, posterQuery: "Inside Out 2" },
  { id: "m-deadpool-wolverine", type: "movie", title: "Deadpool & Wolverine", year: 2024, genres: ["superhero", "comedy", "action"], vibe: ["fun", "meta"], why: "R-rated multiverse buddy chaos", newRelease: true, posterQuery: "Deadpool Wolverine" },
  { id: "m-twisters", type: "movie", title: "Twisters", year: 2024, genres: ["action", "adventure", "disaster"], vibe: ["blockbuster", "fun"], why: "Storm chasers, bigger storms", newRelease: true, posterQuery: "Twisters" },
  { id: "m-oppenheimer", type: "movie", title: "Oppenheimer", year: 2023, genres: ["biography", "drama", "history"], vibe: ["dense", "epic"], why: "The man behind the bomb", newRelease: true, posterQuery: "Oppenheimer" },
  { id: "m-barbie", type: "movie", title: "Barbie", year: 2023, genres: ["comedy", "fantasy", "social"], vibe: ["playful", "sharp"], why: "Pink satire with heart", newRelease: true, posterQuery: "Barbie 2023" },
  { id: "m-poor-things", type: "movie", title: "Poor Things", year: 2023, genres: ["comedy", "fantasy", "romance"], vibe: ["wild", "stylish"], why: "A woman remakes herself", newRelease: true, posterQuery: "Poor Things" },
  { id: "m-godzilla-minus-one", type: "movie", title: "Godzilla Minus One", year: 2023, genres: ["scifi", "action", "war"], vibe: ["emotional", "epic"], why: "Post-war Japan meets the king", newRelease: true, posterQuery: "Godzilla Minus One" },

  // —— Classic / popular movies ——
  { id: "m-inception", type: "movie", title: "Inception", year: 2010, genres: ["scifi", "thriller", "mind-bending"], vibe: ["cerebral", "epic"], why: "Dream heists and layered reality", posterQuery: "Inception" },
  { id: "m-interstellar", type: "movie", title: "Interstellar", year: 2014, genres: ["scifi", "drama", "space"], vibe: ["emotional", "epic"], why: "Love, time, and the stars", posterQuery: "Interstellar" },
  { id: "m-dune", type: "movie", title: "Dune", year: 2021, genres: ["scifi", "epic", "adventure"], vibe: ["epic", "atmospheric"], why: "Desert empires and destiny", posterQuery: "Dune 2021" },
  { id: "m-parasite", type: "movie", title: "Parasite", year: 2019, genres: ["thriller", "drama", "dark-comedy"], vibe: ["sharp", "tense"], why: "Class warfare with a twist", posterQuery: "Parasite" },
  { id: "m-everything", type: "movie", title: "Everything Everywhere All at Once", year: 2022, genres: ["scifi", "comedy", "family"], vibe: ["wild", "heartfelt"], why: "Multiverse chaos and family love", posterQuery: "Everything Everywhere All at Once" },
  { id: "m-arrival", type: "movie", title: "Arrival", year: 2016, genres: ["scifi", "drama", "mind-bending"], vibe: ["quiet", "emotional"], why: "Language, time, and first contact", posterQuery: "Arrival" },
  { id: "m-getout", type: "movie", title: "Get Out", year: 2017, genres: ["horror", "thriller", "social"], vibe: ["tense", "smart"], why: "Horror with social bite", posterQuery: "Get Out" },
  { id: "m-spiderverse", type: "movie", title: "Spider-Man: Into the Spider-Verse", year: 2018, genres: ["animation", "superhero", "adventure"], vibe: ["fun", "stylish"], why: "Kinetic art and heart", posterQuery: "Into the Spider-Verse" },
  { id: "m-whiplash", type: "movie", title: "Whiplash", year: 2014, genres: ["drama", "music"], vibe: ["intense", "ambitious"], why: "Obsession and greatness", posterQuery: "Whiplash" },
  { id: "m-her", type: "movie", title: "Her", year: 2013, genres: ["romance", "scifi", "drama"], vibe: ["intimate", "melancholy"], why: "Love in a digital age", posterQuery: "Her 2013" },
  { id: "m-madmax", type: "movie", title: "Mad Max: Fury Road", year: 2015, genres: ["action", "adventure"], vibe: ["visceral", "epic"], why: "Non-stop desert chase", posterQuery: "Mad Max Fury Road" },
  { id: "m-la-la-land", type: "movie", title: "La La Land", year: 2016, genres: ["musical", "romance", "drama"], vibe: ["bittersweet", "stylish"], why: "Dreams vs. love in LA", posterQuery: "La La Land" },
  { id: "m-blade-runner-2049", type: "movie", title: "Blade Runner 2049", year: 2017, genres: ["scifi", "noir", "mystery"], vibe: ["atmospheric", "slow-burn"], why: "What makes us human", posterQuery: "Blade Runner 2049" },
  { id: "m-the-batman", type: "movie", title: "The Batman", year: 2022, genres: ["superhero", "crime", "noir"], vibe: ["dark", "detective"], why: "Gritty Gotham detective story", posterQuery: "The Batman 2022" },
  { id: "m-spirited", type: "movie", title: "Spirited Away", year: 2001, genres: ["animation", "fantasy", "adventure"], vibe: ["magical", "coming-of-age"], why: "Ghibli wonder and courage", posterQuery: "Spirited Away" },
  { id: "m-pride", type: "movie", title: "Pride & Prejudice", year: 2005, genres: ["romance", "period", "drama"], vibe: ["romantic", "witty"], why: "Classic sparks and banter", posterQuery: "Pride and Prejudice 2005" },
  { id: "m-john-wick", type: "movie", title: "John Wick", year: 2014, genres: ["action", "thriller"], vibe: ["stylish", "revenge"], why: "Ballet of bullets", posterQuery: "John Wick" },
  { id: "m-social-network", type: "movie", title: "The Social Network", year: 2010, genres: ["drama", "biography", "tech"], vibe: ["sharp", "ambitious"], why: "Friendship and founding Facebook", posterQuery: "The Social Network" },

  // —— New / recent TV ——
  { id: "t-fallout", type: "tv", title: "Fallout", year: 2024, genres: ["scifi", "adventure", "dark-comedy"], vibe: ["fun", "brutal"], why: "Vaults, wasteland, and vault-tec lies", newRelease: true, posterQuery: "Fallout TV" },
  { id: "t-penguin", type: "tv", title: "The Penguin", year: 2024, genres: ["crime", "drama", "noir"], vibe: ["dark", "character-driven"], why: "Gotham underworld after The Batman", newRelease: true, posterQuery: "The Penguin" },
  { id: "t-shogun", type: "tv", title: "Shōgun", year: 2024, genres: ["history", "drama", "epic"], vibe: ["epic", "political"], why: "Feudal Japan intrigue", newRelease: true, posterQuery: "Shogun 2024" },
  { id: "t-house-dragon", type: "tv", title: "House of the Dragon", year: 2022, genres: ["fantasy", "drama", "epic"], vibe: ["epic", "brutal"], why: "Targaryen civil war", newRelease: true, posterQuery: "House of the Dragon" },
  { id: "t-the-bear", type: "tv", title: "The Bear", year: 2022, genres: ["drama", "comedy", "food"], vibe: ["anxious", "heartfelt"], why: "Kitchen chaos and found family", newRelease: true, posterQuery: "The Bear" },
  { id: "t-slow-horses", type: "tv", title: "Slow Horses", year: 2022, genres: ["spy", "thriller", "comedy"], vibe: ["sharp", "gritty"], why: "Misfit spies still get the job done", newRelease: true, posterQuery: "Slow Horses" },
  { id: "t-white-lotus", type: "tv", title: "The White Lotus", year: 2021, genres: ["comedy", "drama", "satire"], vibe: ["sharp", "vacation-noir"], why: "Luxury resorts, messy guests", newRelease: true, posterQuery: "The White Lotus" },
  { id: "t-last-of-us", type: "tv", title: "The Last of Us", year: 2023, genres: ["drama", "horror", "adventure"], vibe: ["emotional", "harsh"], why: "Surviving a fungal apocalypse", newRelease: true, posterQuery: "The Last of Us" },
  { id: "t-severance", type: "tv", title: "Severance", year: 2022, genres: ["scifi", "thriller", "mystery"], vibe: ["eerie", "cerebral"], why: "Work-life split made literal", newRelease: true, posterQuery: "Severance" },
  { id: "t-andor", type: "tv", title: "Andor", year: 2022, genres: ["scifi", "thriller", "war"], vibe: ["grounded", "tense"], why: "Rebellion before the Rebellion", newRelease: true, posterQuery: "Andor" },

  // —— Classic TV ——
  { id: "t-breaking-bad", type: "tv", title: "Breaking Bad", year: 2008, genres: ["crime", "drama", "thriller"], vibe: ["intense", "character-driven"], why: "Chemistry teacher turns kingpin", posterQuery: "Breaking Bad" },
  { id: "t-succession", type: "tv", title: "Succession", year: 2018, genres: ["drama", "dark-comedy", "family"], vibe: ["sharp", "savage"], why: "Rich family power games", posterQuery: "Succession" },
  { id: "t-stranger-things", type: "tv", title: "Stranger Things", year: 2016, genres: ["scifi", "horror", "adventure"], vibe: ["nostalgic", "fun"], why: "Kids vs the Upside Down", posterQuery: "Stranger Things" },
  { id: "t-the-office", type: "tv", title: "The Office", year: 2005, genres: ["comedy", "workplace"], vibe: ["comfort", "awkward"], why: "Dunder Mifflin forever", posterQuery: "The Office US" },
  { id: "t-arcane", type: "tv", title: "Arcane", year: 2021, genres: ["animation", "fantasy", "action"], vibe: ["stylish", "tragic"], why: "Sisters torn by progress", posterQuery: "Arcane" },
  { id: "t-ted-lasso", type: "tv", title: "Ted Lasso", year: 2020, genres: ["comedy", "sports", "feel-good"], vibe: ["warm", "kind"], why: "Optimism as a superpower", posterQuery: "Ted Lasso" },
  { id: "t-dark", type: "tv", title: "Dark", year: 2017, genres: ["scifi", "mystery", "mind-bending"], vibe: ["dense", "dark"], why: "Time travel family knot", posterQuery: "Dark Netflix" },
  { id: "t-fleabag", type: "tv", title: "Fleabag", year: 2016, genres: ["comedy", "drama"], vibe: ["raw", "witty"], why: "Grief, love, fourth wall", posterQuery: "Fleabag" },
  { id: "t-mandalorian", type: "tv", title: "The Mandalorian", year: 2019, genres: ["scifi", "adventure", "western"], vibe: ["fun", "space-western"], why: "This is the way", posterQuery: "The Mandalorian" },
  { id: "t-wednesday", type: "tv", title: "Wednesday", year: 2022, genres: ["mystery", "fantasy", "teen"], vibe: ["quirky", "gothic"], why: "Addams detective vibes", posterQuery: "Wednesday" },

  // —— New / recent books ——
  { id: "b-fourth-wing", type: "book", title: "Fourth Wing", year: 2023, author: "Rebecca Yarros", genres: ["fantasy", "romance", "ya"], vibe: ["romantic", "fierce"], why: "Dragons, war college, slow burn", newRelease: true, posterQuery: "Fourth Wing Rebecca Yarros", isbn: "9781649374042" },
  { id: "b-iron-flame", type: "book", title: "Iron Flame", year: 2023, author: "Rebecca Yarros", genres: ["fantasy", "romance", "ya"], vibe: ["romantic", "epic"], why: "Violet’s second year gets deadlier", newRelease: true, posterQuery: "Iron Flame", isbn: "9781649374172" },
  { id: "b-tomorrow", type: "book", title: "Tomorrow, and Tomorrow, and Tomorrow", year: 2022, author: "Gabrielle Zevin", genres: ["literary", "friendship", "games"], vibe: ["heartfelt", "modern"], why: "Game designers, love, and time", newRelease: true, posterQuery: "Tomorrow and Tomorrow and Tomorrow", isbn: "9780593321201" },
  { id: "b-lessons-chemistry", type: "book", title: "Lessons in Chemistry", year: 2022, author: "Bonnie Garmus", genres: ["historical", "comedy", "feminist"], vibe: ["witty", "inspiring"], why: "A chemist takes on cooking TV", newRelease: true, posterQuery: "Lessons in Chemistry", isbn: "9780385547345" },
  { id: "b-yellowface", type: "book", title: "Yellowface", year: 2023, author: "R.F. Kuang", genres: ["literary", "satire", "thriller"], vibe: ["sharp", "uncomfortable"], why: "Publishing, identity, and theft", newRelease: true, posterQuery: "Yellowface Kuang", isbn: "9780063250833" },
  { id: "b-demon-copperhead", type: "book", title: "Demon Copperhead", year: 2022, author: "Barbara Kingsolver", genres: ["literary", "drama", "coming-of-age"], vibe: ["raw", "powerful"], why: "Appalachia rewrites David Copperfield", newRelease: true, posterQuery: "Demon Copperhead", isbn: "9780063251922" },
  { id: "b-housemaid", type: "book", title: "The Housemaid", year: 2022, author: "Freida McFadden", genres: ["thriller", "psychological", "suspense"], vibe: ["twisty", "page-turner"], why: "A job with dangerous secrets", newRelease: true, posterQuery: "The Housemaid Freida", isbn: "9781538742570" },
  { id: "b-project-hail-mary", type: "book", title: "Project Hail Mary", year: 2021, author: "Andy Weir", genres: ["scifi", "adventure", "friendship"], vibe: ["fun", "smart"], why: "Science problem-solving in space", newRelease: true, posterQuery: "Project Hail Mary", isbn: "9780593135204" },

  // —— Classic books ——
  { id: "b-dune", type: "book", title: "Dune", year: 1965, author: "Frank Herbert", genres: ["scifi", "epic", "politics"], vibe: ["epic", "dense"], why: "The novel that defined desert power", posterQuery: "Dune Frank Herbert", isbn: "9780441172719" },
  { id: "b-circe", type: "book", title: "Circe", year: 2018, author: "Madeline Miller", genres: ["fantasy", "mythology", "literary"], vibe: ["lyrical", "feminist"], why: "Witch of Aiaia retold", posterQuery: "Circe Madeline Miller", isbn: "9780316556347" },
  { id: "b-name-of-the-wind", type: "book", title: "The Name of the Wind", year: 2007, author: "Patrick Rothfuss", genres: ["fantasy", "adventure"], vibe: ["lyrical", "coming-of-age"], why: "A legend tells his story", posterQuery: "The Name of the Wind", isbn: "9780756404741" },
  { id: "b-gone-girl", type: "book", title: "Gone Girl", year: 2012, author: "Gillian Flynn", genres: ["thriller", "mystery", "dark"], vibe: ["twisty", "unreliable"], why: "Marriage as a crime scene", posterQuery: "Gone Girl", isbn: "9780307588371" },
  { id: "b-atomic-habits", type: "book", title: "Atomic Habits", year: 2018, author: "James Clear", genres: ["self-help", "productivity"], vibe: ["practical", "clear"], why: "Tiny changes, big results", posterQuery: "Atomic Habits", isbn: "9780735211292" },
  { id: "b-educated", type: "book", title: "Educated", year: 2018, author: "Tara Westover", genres: ["memoir", "biography"], vibe: ["raw", "inspiring"], why: "Leaving home for knowledge", posterQuery: "Educated Tara Westover", isbn: "9780399590504" },
  { id: "b-1984", type: "book", title: "1984", year: 1949, author: "George Orwell", genres: ["dystopia", "scifi", "classic"], vibe: ["bleak", "political"], why: "Big Brother is watching", posterQuery: "1984 George Orwell", isbn: "9780451524935" },
  { id: "b-hobbit", type: "book", title: "The Hobbit", year: 1937, author: "J.R.R. Tolkien", genres: ["fantasy", "adventure", "classic"], vibe: ["cozy", "epic"], why: "Unexpected journey", posterQuery: "The Hobbit", isbn: "9780547928227" },
  { id: "b-silent-patient", type: "book", title: "The Silent Patient", year: 2019, author: "Alex Michaelides", genres: ["thriller", "mystery", "psychological"], vibe: ["twisty", "page-turner"], why: "A woman who won't speak", posterQuery: "The Silent Patient", isbn: "9781250301697" },
  { id: "b-klara", type: "book", title: "Klara and the Sun", year: 2021, author: "Kazuo Ishiguro", genres: ["literary", "scifi", "drama"], vibe: ["quiet", "tender"], why: "An AI's devotion", posterQuery: "Klara and the Sun", isbn: "9780593318171" },
  { id: "b-song-of-achilles", type: "book", title: "The Song of Achilles", year: 2011, author: "Madeline Miller", genres: ["mythology", "romance", "literary"], vibe: ["romantic", "tragic"], why: "Patroclus and Achilles", posterQuery: "The Song of Achilles", isbn: "9780062060624" },
  { id: "b-six-of-crows", type: "book", title: "Six of Crows", year: 2015, author: "Leigh Bardugo", genres: ["fantasy", "heist", "ya"], vibe: ["clever", "found-family"], why: "Impossible heist crew", posterQuery: "Six of Crows", isbn: "9781627792127" },
  { id: "b-sapiens", type: "book", title: "Sapiens", year: 2011, author: "Yuval Noah Harari", genres: ["history", "nonfiction", "science"], vibe: ["big-picture", "provocative"], why: "How humans took over", posterQuery: "Sapiens Harari", isbn: "9780062316097" },
  { id: "b-thursday-murder", type: "book", title: "The Thursday Murder Club", year: 2020, author: "Richard Osman", genres: ["mystery", "comedy", "cozy"], vibe: ["cozy", "witty"], why: "Retirees solve murders", posterQuery: "The Thursday Murder Club", isbn: "9781984880987" },
  { id: "b-narnia", type: "book", title: "The Lion, the Witch and the Wardrobe", year: 1950, author: "C.S. Lewis", genres: ["fantasy", "classic", "adventure"], vibe: ["magical", "classic"], why: "Wardrobe to Narnia", posterQuery: "The Lion the Witch and the Wardrobe", isbn: "9780064471046" },
  { id: "b-martian", type: "book", title: "The Martian", year: 2011, author: "Andy Weir", genres: ["scifi", "adventure", "humor"], vibe: ["fun", "problem-solving"], why: "Science the crap out of this", posterQuery: "The Martian", isbn: "9780553418026" },
  { id: "b-normal-people", type: "book", title: "Normal People", year: 2018, author: "Sally Rooney", genres: ["literary", "romance", "drama"], vibe: ["intimate", "raw"], why: "Modern love and class", posterQuery: "Normal People Rooney", isbn: "9781984822178" },
  { id: "b-mistborn", type: "book", title: "Mistborn: The Final Empire", year: 2006, author: "Brandon Sanderson", genres: ["fantasy", "heist", "magic"], vibe: ["clever", "epic"], why: "Ash, metal, and rebellion", posterQuery: "Mistborn The Final Empire", isbn: "9780765311788" },
  { id: "b-gatsby", type: "book", title: "The Great Gatsby", year: 1925, author: "F. Scott Fitzgerald", genres: ["classic", "literary", "romance"], vibe: ["glamorous", "tragic"], why: "Green light across the bay", posterQuery: "The Great Gatsby", isbn: "9780743273565" },
];
